FROM alpine:latest as downloader
RUN apk add --no-cache curl && \
    curl -L "https://download.jetbrains.com/product?code=IIC&latest&distribution=linux" | tar -xvz && \
    mv idea* idea

FROM ilteoood/base-vnc
COPY --from=downloader idea /opt/idea
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk git && \
    apt-get autoremove --purge && apt-get autoclean
ENV VNC_PORT=5901
ENV NO_VNC_PORT=6901
EXPOSE ${VNC_PORT}
EXPOSE ${NO_VNC_PORT}
ENTRYPOINT \
        Xvfb :1 -screen 0 1920x1080x24 & \
        x11vnc -display :1.0 -rfbport ${VNC_PORT} & \
        websockify -D --web=/usr/share/novnc/ ${NO_VNC_PORT} localhost:${VNC_PORT} && \
        env DISPLAY=:1.0 /opt/idea/bin/idea.sh