FROM alpine:latest as downloader
RUN apk add --no-cache curl && \
    curl -L "https://download.jetbrains.com/product?code=IIU&latest&distribution=linux" | tar -xvz && \
    mv idea* idea

FROM ilteoood/base-x11
COPY --from=downloader idea /opt/idea
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk git && \
    apt-get autoremove --purge && apt-get autoclean
ENTRYPOINT /opt/idea/bin/idea.sh