FROM alpine:latest as downloader
RUN apk add --no-cache curl && \
    curl -L "https://download.jetbrains.com/product?code=PS&latest&distribution=linux" | tar -xvz && \
    mv PhpStorm* phpstorm

FROM debian:stable-slim
COPY --from=downloader phpstorm /opt/phpstorm
RUN mkdir -p /usr/share/man/man1 && \
    apt-get update && \
    apt-get install -y libxtst-dev libxext-dev libxrender-dev libfreetype6-dev libfontconfig1 libgtk2.0-0 libxslt1.1 libxxf86vm1 && \
    apt-get install -y git php && \
    apt-get autoremove --purge && apt-get autoclean
ENTRYPOINT /opt/phpstorm/bin/phpstorm.sh