FROM alpine:latest as downloader
RUN apk add --no-cache curl && \
    curl -L "https://download.jetbrains.com/product?code=PS&latest&distribution=linux" | tar -xvz && \
    mv PhpStorm* phpstorm

FROM ilteoood/base-x11
COPY --from=downloader phpstorm /opt/phpstorm
RUN apt-get update && \
    apt-get install -y git php && \
    apt-get autoremove --purge && apt-get autoclean
ENTRYPOINT /opt/phpstorm/bin/phpstorm.sh