FROM alpine:latest as downloader
RUN apk add --no-cache curl && \
    curl -L "https://download.jetbrains.com/product?code=RM&latest&distribution=linux" | tar -xvz && \
    mv RubyMine* rubymine

FROM ilteoood/base-x11
COPY --from=downloader rubymine /opt/rubymine
RUN apt-get update && \
    apt-get install -y ruby-full && \
    apt-get autoremove --purge && apt-get autoclean
ENTRYPOINT /opt/rubymine/bin/rubymine.sh