FROM alpine:latest as downloader
RUN apk add --no-cache curl && \
    curl -L "https://download.jetbrains.com/product?code=CL&latest&distribution=linux" | tar -xvz && \
    mv clion* clion

FROM ilteoood/base-x11
COPY --from=downloader clion /opt/clion
RUN apt-get update && \
    apt-get install -y build-essential git && \
    apt-get autoremove --purge && apt-get autoclean
ENTRYPOINT /opt/clion/bin/clion.sh