FROM alpine:latest as downloader
RUN apk add --no-cache curl && \
    curl -L "https://download.jetbrains.com/product?code=CL&latest&distribution=linux" | tar -xvz && \
    mv clion* clion

FROM ilteoood/base-vnc
COPY --from=downloader clion /opt/clion
RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get autoremove --purge && apt-get autoclean
ENV VNC_PORT=5901
ENV NO_VNC_PORT=6901
EXPOSE ${VNC_PORT}
EXPOSE ${NO_VNC_PORT}
ENTRYPOINT \
        Xvfb :1 -screen 0 1920x1080x24 & \
        x11vnc -display :1.0 -rfbport ${VNC_PORT} & \
        websockify -D --web=/usr/share/novnc/ ${NO_VNC_PORT} localhost:${VNC_PORT} && \
        env DISPLAY=:1.0 /opt/clion/bin/clion.sh