FROM alpine:latest as downloader
RUN apk add --no-cache curl && \
    curl -L "https://download.jetbrains.com/product?code=WS&latest&distribution=linux" | tar -xvz && \
    mv WebStorm* webstorm

FROM ilteoood/base-x11
COPY --from=downloader webstorm /opt/webstorm
RUN apt-get update && \
    apt-get install -y nodejs yarn && \
    apt-get autoremove --purge && apt-get autoclean
ENTRYPOINT /opt/webstorm/bin/webstorm.sh