FROM alpine:latest as downloader
RUN apk add --no-cache curl && \
    curl -L "https://download.jetbrains.com/product?code=WS&latest&distribution=linux" | tar -xvz && \
    mv WebStorm* webstorm

FROM debian:stable-slim
COPY --from=downloader webstorm /opt/webstorm
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get update && \
    apt-get install -y libxtst-dev libxext-dev libxrender-dev libfreetype6-dev libfontconfig1 libgtk2.0-0 libxslt1.1 libxxf86vm1 && \
    apt-get install -y x11vnc xvfb novnc && \
    apt-get install -y nodejs git yarn
ENV VNC_PORT=5901
ENV NO_VNC_PORT=6901
EXPOSE ${VNC_PORT}
EXPOSE ${NO_VNC_PORT}
ENTRYPOINT \
        Xvfb :1 -screen 0 1920x1080x24 & \
        x11vnc -display :1.0 -rfbport ${VNC_PORT} & \
        websockify -D --web=/usr/share/novnc/ ${NO_VNC_PORT} localhost:${VNC_PORT} && \
        env DISPLAY=:1.0 /opt/webstorm/bin/webstorm.sh