FROM alpine:latest as downloader
RUN apk add --no-cache curl && \
    curl -L "https://download.jetbrains.com/product?code=WS&latest&distribution=linux" | tar -xvz && \
    mv WebStorm* webstorm

FROM debian:stable-slim
COPY --from=downloader webstorm /opt/webstorm
RUN apt-get update && \
    apt-get install -y libxtst-dev libxext-dev libxrender-dev libfreetype6-dev libfontconfig1 libgtk2.0-0 libxslt1.1 libxxf86vm1 xfonts-base && \
    apt-get install -y nodejs git yarn && \
    apt-get autoremove --purge && apt-get autoclean
ENTRYPOINT /opt/webstorm/bin/webstorm.sh