FROM alpine:latest as downloader
RUN apk add --no-cache curl && \
    curl -L "https://download.jetbrains.com/product?code=PCP&latest&distribution=linux" | tar -xvz && \
    mv pycharm* pycharm

FROM ilteoood/base-x11
COPY --from=downloader pycharm /opt/pycharm
RUN apt-get update && \
    apt-get install -y git python3 && \
    apt-get autoremove --purge && apt-get autoclean
ENTRYPOINT /opt/pycharm/bin/pycharm.sh