name: Build and publish image
on:
  push:
  schedule:
    - cron: '0 8 * * 1'

jobs:
    buildBase:
        runs-on: ubuntu-latest
        name: Build and publish base image job
        steps:
          - name: Checkout master
            uses: actions/checkout@master
          - name: Build and publish projector base image
            uses: ilteoood/docker_buildx@master
            with:
              tag: latest
              imageName: ilteoood/projector-base
              platform: linux/amd64,linux/arm64,linux/arm/v7
              publish: true
              dockerUser: ilteoood
              dockerPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
              dockerFile: base_image/Dockerfile
    buildIde:
        needs: [buildBase]
        runs-on: ubuntu-latest
        name: Build and publish image job
        strategy:
          max-parallel: 2
          fail-fast: false
          matrix:
            ide: ['CLion', 'GoLand', 'IntelliJ Idea Community', 'IntelliJ Idea Education', 'IntelliJ Idea Ultimate', 'PhpStorm', 'PyCharm Education', 'PyCharm Professional', 'RubyMine', 'WebStorm']
            variant: ['2021.2.3', '2020.3.5']
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: Build and publish image
              uses: ilteoood/docker_buildx@master
              with:
                tag: ${{ matrix.variant }}
                imageName: ilteoood/${{ matrix.ide }}
                platform: linux/amd64,linux/arm64,linux/arm/v7
                publish: true
                dockerUser: ilteoood
                dockerPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
                dockerFile: ${{ matrix.ide }}/Dockerfile
