name: Build and publish image
on:
  push:
  schedule:
    - cron: '0 8 * * 1'

jobs:
    buildIde:
        #needs: [buildBase]
        runs-on: ubuntu-latest
        name: Build and publish image job
        strategy:
          max-parallel: 2
          fail-fast: false
          matrix:
            ide: ['clion', 'goland', 'intellij_community', 'intellij_edu', 'intellij_ultimate', 'phpstorm', 'pycharm_edu', 'pycharm_pro', 'rubymine', 'webstorm']
            variant: ['2021.2.2']
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: Build and publish image
              uses: ilteoood/docker_buildx@master
              with:
                tag: ${{ matrix.variant }}
                imageName: ilteoood/${{ matrix.ide }}
                platform: linux/amd64,linux/arm64,linux/arm/v7
                publish: true
                dockerUser: ilteoood
                dockerPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
                dockerFile: ${{ matrix.ide }}/Dockerfile
                buildArg: IDE_VERSION=${{ matrix.variant }}
